20_final_test/or_db_test/config/routes.rb
Rails.application.routes.draw do

  root 'home#home'
  
  get '/login' => 'sessions#new' # login page
  post '/login' => 'sessions#create' # login form POSTs here; authentication logic
  get '/logout' => 'sessions#destroy' # logout and redirect to root

  resources :users
  resources :shows
  resources :airings
  resources :clients
  resources :networks

end

20_final_test/or_db_test/app/models/airing.rb
class Airing < ActiveRecord::Base

  belongs_to :client
  belongs_to :show

  validates_presence_of :client_id, :show_id, :gross_cost, :net_cost, :airdate

end

20_final_test/or_db_test/app/models/client.rb
class Client < ActiveRecord::Base

  mount_uploader :logourl, LogoUploader

  has_many :airings
  has_many :shows, through: :airings

  validates :clientname, :uniqueness => true, :presence => true 
  
end

20_final_test/or_db_test/app/models/network.rb
class Network < ActiveRecord::Base
  
  has_many :shows

  validates :netname, :uniqueness => true, :presence => true 

end

20_final_test/or_db_test/app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :network
  has_many :clients, through: :airings
end

20_final_test/or_db_test/app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name, :email

  has_secure_password # AR method to activate bcrypt

end

20_final_test/or_db_test/app/controllers/airings_controller.rb
class AiringsController < ApplicationController

  before_action :authorize

  def new
    @airing = Airing.new
    #not sure I'll use this either, but look up client from params?
    @client = Client.find(params[:client_id])
  end

  def create
    @airing = Airing.new(airing_params)

    if @airing.save
      #after we successfully add a show, take me to adding airings of the show
      redirect_to client_path(airing_params[:client_id])
    else
      flash[:message] = "Info Missing, Please try again."
      # if the post fails, I need to look up the network again
      # because new.html.erb includes the @client instance variable.
      @client = Client.find(airing_params[:client_id])
      render client_path(@client)
    end
  end

private

  def airing_params
    params.require(:airing).permit(:show_id, :client_id, :net_cost, :gross_cost, :airdate, :airweek_id)
  end

end

20_final_test/or_db_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  helper_method :current_user

  def authorize
    redirect_to '/' if !current_user
  end

end

20_final_test/or_db_test/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
 
 before_action :authorize

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
#     @client.logourl = nil
    
# #add the rest of the stuff for this   
#    LogoUploader.perform_async(@client.id, client_params[:logourl]) # worker

    if @client.save
      redirect_to '/'
    else
      render :new
    end
  end
  
  def index
    @client = Client.order(:clientname)
  end

  def show
    @client = Client.find(params[:id])
    @airing = Airing.all
  end

private

  def client_params
    params.require(:client).permit(:clientname, :commissionstype, :AM_name, :PM_or_AC_name, :PM_or_AC2_name, :Analytics_name, :logourl)
  end

end

20_final_test/or_db_test/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  #  @clients = Client.all
    @users = User.all
    @clients = Client.order(:clientname)
  end

end

20_final_test/or_db_test/app/controllers/networks_controller.rb
class NetworksController < ApplicationController

 before_action :authorize

  def new
    @network = Network.new
    #Not sure I'll use this, find the network for the show...add from within network? TBD
  end

  def create
    @network = Network.new(network_params)

    if @network.save
      #after we successfully add a network, take me to adding show
      redirect_to new_show_path
    else
      render :new
    end
  end
  def index
    @network = Network.all
  end
  def show
    @network = Network.find(params[:id])
    if @bcast_month == true
      @billingsched = "Broadcast"
    else @billingsched = "Calendar"
    end
  end

private

  def network_params
    params.require(:network).permit(:netname, :bcast_month)
  end

end

20_final_test/or_db_test/app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < ApplicationController

  def new
  end


  # authentication logic and cookie stuff
  def create
    @user = User.find_by(email: params['email'])

    if @user && @user.authenticate(params['password'])
      session[:user_id] = @user.id

      flash[:message] = "Login successful!"

      redirect_to '/'
    else
      flash[:message] = "Incorrect Username or Password. Please try again."

      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

20_final_test/or_db_test/app/controllers/shows_controller.rb
class ShowsController < ApplicationController

 before_action :authorize

  def new
    @show = Show.new
    
  end

  def create
    @show = Show.new(show_params)
    @client = 
    
    if @show.save
      #after we successfully add a show, take me to adding airings of the show
      redirect_to '/'
    else
      flash[:message] = "Info Missing, Please try again."
      render :new
    end
  end

private

  def show_params
    params.require(:show).permit(:showname, :network_id, :placement)
  end

end

20_final_test/or_db_test/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to '/'
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

20_final_test/or_db_test/app/helpers/application_helper.rb
module ApplicationHelper
end

20_final_test/or_db_test/app/views/clients/new.html.erb
<h2> Add a Client </h2>

<!-- add a form for adding a client -->
<%= form_for @client do |f| %>

  <%= f.label "Client Name" %>
  <%= f.text_field :clientname %>
  <br><br>
  <%= f.label "Commissions Type" %>
  <%= f.text_field :commissionstype , placeholder: "15% of gross"%>
  <br><br>
  <%= f.label "Account Manager" %>
  <%= f.text_field :AM_name %>
  <br><br>
  <%= f.label "PM or AC" %>
  <%= f.text_field :PM_or_AC_name %>
  <br><br>
  <%= f.label "Second PM or AC" %>
  <%= f.text_field :PM_or_AC2_name %>
  <br><br>
  <%= f.label "Analytics Lead" %>
  <%= f.text_field :Analytics_name %>
  <br><br>
   <%= f.label :logourl %>
  <%= f.file_field :logourl %>
  <br><br>
  <%= f.submit 'Create Company', :class => 'btn btn-primary btn-lg'  %>

<% end %>

20_final_test/or_db_test/app/views/clients/show.html.erb
<div class = "row">
  <div class ="col-md-8">
    <img src="<%=@client.logourl.url%>" class="logopic">
    <div class="clear"></div>
    <h1><%= @client.clientname %></h1>
    <h5>Commissions structure:<%= @client.commissionstype %> </h5>
  </div>
  <div class="col-md-4">
    <h5><b>Team</b></h5>
    <% if @client.AM_name %>
        <p> AM: <%= @client.AM_name %></p>
        <% end%>
    <% if @client.PM_or_AC_name %>
      <p>PM/AC: <%= @client.PM_or_AC_name %></p>
      <% end %>
    <% if @client.PM_or_AC2_name %>
      <p>PM/AC: <%= @client.PM_or_AC2_name %></p>
      <% end %>
    <% if @client.Analytics_name %>
      <p>Analytics: <%= @client.Analytics_name %></p>
      <% end %>
  </div> <!--end team col div-->

</div><!--end row-->
      
<h3> Schedule</h3>


<%= link_to "Add to schedule for #{@client.clientname}", new_airing_path(client_id: @client.id) %>

<table class = "schedule">
  <th>Show</th>
  <th>Date</th>
  <th>Gross</th>
  <th>Net</th>
  <% @client.airings.each do |g|%>
  <tr>
    <td><%=g.show.showname%></td>
    <td><%=g.airdate%></td>
    <td>$<%=g.gross_cost%></td>
    <td>$<%=g.net_cost%></td>
  </tr>
  <%end%>
  <tr>
    <td>~~~TOTALS~~~</td>
    <td> </td>
    <td>$<%=@client.airings.sum(:gross_cost)%></td>
    <td>$<%=@client.airings.sum(:net_cost)%></td>
  <tr>
</table> 

20_final_test/or_db_test/app/views/shows/new.html.erb
<h2> Add a Show </h2>

<!-- add a form for adding a network -->
<%= form_for @show do |f| %>

  <%= f.label :showname %>
  <%= f.text_field :showname %>
  <br><br>
  <%= f.label "Network" %>
  <%= f.collection_select :network_id, Network.all, :id, :netname %>

  <span class = "small_link" >need to <a href="<%=new_network_path%>">Create A Network</a> first?</span>
  <br>
  <br>

  <%= f.submit 'Create Show', :class => 'btn btn-primary btn-lg' %>

<% end %>